@startuml
title Modelo de Domínio - Sistema de Veículos Autônomos (Análise)

class Usuario {
  - nome: string
  - telefone: string
  - email: string
}

class Localizacao {
  - latitude: decimal
  - longitude: decimal
  - descricao: string
}

class VeiculoAutonomo {
  - placa: string
  - chassi: string
  - autonomia: decimal
  - statusBateria: string
  + status: EEstadosVeiculo
}

class Manutencao {
  dataInicio: DateTime
  dataFim: DateTime
  tipo: ETiposManutencao
  descricao: String
}

Enum ETiposManutencao{
  PREVENTIVA
  CORRETIVA
  BATERIA
}

Enum EEstadosVeiculo{
  DESLIGADO
  DISPONIVEL
  AGUARDANDO
  EM_CORRIDA
  EM_MANUTENCAO
  EM_EMERGENCIA
}

class Solicitacao {
  - dataHora: DateTime
  - estimativaChegada: int
}

class Viagem {
  - dataInicio: DateTime
  - dataFim: DateTime
}

class AvaliacaoFinal {
    - nota: int
    - observacao: string
}

class EmergenciaOcorrida {
    - descricao: int
    - dataOcorrencia: DateTime
    - resolvido: boolean
    - gravidade: EGravidadeEmergencia
}

class AcidenteOcorrido{
    - dataOcorrencia: DateTime
    - fotos : FotoRegistrada[]
}

class FotoRegistrada{
  - imagem: string
  - timestamp: DateTime
  - metadados: JSON (ex: resolução, sensor_origem)
}

note left of FotoRegistrada::"imagem: string"
  Base64 da foto
end note

Enum EGravidadeEmergencia{
    LEVE
    MEDIA
    GRAVE
}

class CodigoConfirmacao {
  - codigo: string
  - valido: boolean
  - dataGeracao: DateTime
}

class Rota {
  - distancia: decimal
  - tempoEstimado: int
  - condicoesClimaticas: string
  - statusTrafego: string
}

class SistemaDetecaoRisco {
  - sensoresAtivos: boolean
  - ultimaCalibracao: DateTime
}

class EventoRisco {
  - dataOcorrencia: DateTime
  - localizacao: Localizacao
  - resolvido: boolean
}

class Pagamento {
  efetuado: boolean
  formaPagamento: EFormaPagamento
  dataConfirmacao: DateTime
  valorBruto: decimal
}

class TaxaPagamento{
  valor: decimal
  formaPagamento: EFormaPagamento
}

Enum EFormaPagamento {
PIX
CREDITO
DEBITO
}

Usuario "1" -- "0..*" Solicitacao : realiza
Solicitacao "1" -- "1" Localizacao : localPartida
Solicitacao "1" -- "1" Localizacao : localDestino
Solicitacao "1" -- "1" VeiculoAutonomo : veiculoDesignado

Viagem "1" -- "1" Usuario : passageiro
Viagem "1" -- "1" VeiculoAutonomo : veiculo
Viagem "1" -- "1" CodigoConfirmacao : codigoConfirmacao
Viagem "1" -- "1" Rota : rota
Viagem "1" -- "0..1" AvaliacaoFinal
Viagem "1" -- "0..*" EmergenciaOcorrida
Viagem "1" -- "1" Pagamento

Pagamento -- EFormaPagamento
Pagamento "0..*" -- "0..*" TaxaPagamento
TaxaPagamento -- EFormaPagamento

EGravidadeEmergencia -- EmergenciaOcorrida
AcidenteOcorrido "0..1" -- "1" EmergenciaOcorrida
EGravidadeEmergencia -- AcidenteOcorrido
AcidenteOcorrido "1" -- "0..*" FotoRegistrada

VeiculoAutonomo "1" -- "1" Localizacao : localizacaoAtual
VeiculoAutonomo -- SistemaDetecaoRisco
VeiculoAutonomo -- EEstadosVeiculo
VeiculoAutonomo "1" -- "0..*" Manutencao
Rota -- "0..2" Localizacao

Manutencao -- ETiposManutencao

SistemaDetecaoRisco "1" -- "0..*" EventoRisco
EventoRisco "1" -- "0..1" EmergenciaOcorrida
@enduml